// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yolov5_service.proto

#include "yolov5_service.pb.h"
#include "yolov5_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace yolov5 {

static const char* YOLOv5Service_method_names[] = {
  "/yolov5.YOLOv5Service/Infer",
};

std::unique_ptr< YOLOv5Service::Stub> YOLOv5Service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< YOLOv5Service::Stub> stub(new YOLOv5Service::Stub(channel, options));
  return stub;
}

YOLOv5Service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Infer_(YOLOv5Service_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status YOLOv5Service::Stub::Infer(::grpc::ClientContext* context, const ::yolov5::ImageData& request, ::yolov5::InferenceResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::yolov5::ImageData, ::yolov5::InferenceResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Infer_, context, request, response);
}

void YOLOv5Service::Stub::async::Infer(::grpc::ClientContext* context, const ::yolov5::ImageData* request, ::yolov5::InferenceResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::yolov5::ImageData, ::yolov5::InferenceResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Infer_, context, request, response, std::move(f));
}

void YOLOv5Service::Stub::async::Infer(::grpc::ClientContext* context, const ::yolov5::ImageData* request, ::yolov5::InferenceResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Infer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::yolov5::InferenceResult>* YOLOv5Service::Stub::PrepareAsyncInferRaw(::grpc::ClientContext* context, const ::yolov5::ImageData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::yolov5::InferenceResult, ::yolov5::ImageData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Infer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::yolov5::InferenceResult>* YOLOv5Service::Stub::AsyncInferRaw(::grpc::ClientContext* context, const ::yolov5::ImageData& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInferRaw(context, request, cq);
  result->StartCall();
  return result;
}

YOLOv5Service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      YOLOv5Service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< YOLOv5Service::Service, ::yolov5::ImageData, ::yolov5::InferenceResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](YOLOv5Service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::yolov5::ImageData* req,
             ::yolov5::InferenceResult* resp) {
               return service->Infer(ctx, req, resp);
             }, this)));
}

YOLOv5Service::Service::~Service() {
}

::grpc::Status YOLOv5Service::Service::Infer(::grpc::ServerContext* context, const ::yolov5::ImageData* request, ::yolov5::InferenceResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace yolov5

